version: "3.3"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8088:8088
    depends_on:
      - maria_db
    links:
      - maria_db:maria_db 
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  maria_db:
    image: "mariadb:10.5.8"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret